# vim: nospell

clone_folder: "c:\\appveyor-test"

environment:
  global:
    STACK_ROOT: "c:\\sr"
#   matrix:
#     - GHC: "7.10"
#     - GHC: "8.0"
#     - GHC: "8.2"

before_build:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  # - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - set PATH=C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%

  # LLVM: https://www.appveyor.com/docs/build-environment/#llvm
  # - set PATH=C:\Libraries\llvm-5.0.0\bin;%PATH%
  # - dir C:\Libraries\llvm-5.0.0
  # - dir C:\Libraries\llvm-5.0.0\bin
  # - dir C:\Libraries\llvm-5.0.0\lib
  # - llvm-config --version

  # LLVM: Download and install our own copy of LLVM, which has been built with
  # shared libraries (the provided version does not include this component).
  - appveyor DownloadFile "https://drive.google.com/uc?export=download&id=1VTs8qaSiVAGO1BQYUbfafAXigDuxra5H" -FileName llvm-5.0.0.7z
  - 7z x llvm-5.0.0.7z -oC:\

  - set PATH=C:\llvm-5.0.0\bin;%PATH%
  - dir C:\llvm-5.0.0
  - dir C:\llvm-5.0.0\bin
  - dir C:\llvm-5.0.0\lib
  - llvm-config --version
  - llvm-config --libs --link-shared

  # install stack
  - appveyor DownloadFile "https://www.stackage.org/stack/windows-x86_64" -FileName stack.zip
  - 7z x stack.zip stack.exe
  - stack --version

  - stack setup --no-terminal > NUL
  - stack build --no-terminal --fast --only-dependencies --extra-lib-dirs=C:\llvm-5.0.0\bin

build_script:
  - stack build --no-terminal --fast

test_script:
  - stack exec appveyor-test

