# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
# vim: nospell

resolver: ghc-8.6.0.20180627
compiler: ghc-8.6.0.20180627
compiler-check: match-exact
allow-newer: true

setup-info:
  ghc:
    linux64: # x86_64-unknown-linux
      8.6.0.20180627:
        url:    https://downloads.haskell.org/~ghc/8.6.1-alpha1/ghc-8.6.0.20180627-x86_64-deb8-linux.tar.xz
        sha256: e891e9e6ad0d53382e79b5c1005af6123501fbc95088ed849c3a1c22979db319
    windows64:
      8.6.0.20180627:
        url:    https://downloads.haskell.org/~ghc/8.6.1-alpha1/ghc-8.6.0.20180627-x86_64-unknown-mingw32.tar.xz
        sha256: ccff1f896425f932581c804e1fd6dd14dea7b7423f7f4970ff1d99ab03c97504

packages:
- '.'

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: cfd7a8413ac65133f5a6986ddc2ff6279a4d55d1

- git:    https://github.com/tmcdonell/hs-memory.git
  commit: feee6256e19ed178dc75b071dc54983bc6320f26

- git:    https://github.com/tmcdonell/foundation.git
  commit: 9743bb1eb5cd76c22d8c119c21b359ba4984e642
  subdirs:
    - basement

- git:    https://github.com/tmcdonell/tasty.git
  commit: 540c85d14e6601bb8c92e9fea22dbb8bd27cbe85
  subdirs:
    - core

- mintty-0.1.2
- happy-1.19.9

- adjunctions-4.4
- ansi-terminal-0.8.0.4
- ansi-wl-pprint-0.6.8.2
- async-2.2.1
- base-compat-0.10.4
- base-orphans-0.8
- bifunctors-5.5.3
- cabal-doctest-1.0.6
- call-stack-0.1.0
- clock-0.7.2
- code-page-0.1.3
- colour-2.3.4
- comonad-5.0.4
- concurrent-output-1.10.6
- constraints-0.10.1
- contravariant-1.5
- cryptonite-0.25
- distributive-0.6
- doctest-0.16.0
- exceptions-0.10.0
- foundation-0.0.20
- free-5.1
- ghc-paths-0.1.0.9
- half-0.3
- hashable-1.2.7.0
- hashtables-1.2.3.1
- haskell-lexer-1.0.1
- hedgehog-0.6
- invariant-0.5
- kan-extensions-5.2
- lens-4.17
- lifted-async-0.10.0.2
- lifted-base-0.2.3.12
- mmorph-1.1.2
- monad-control-1.0.2.3
- optparse-applicative-0.14.2.0
- parallel-3.2.1.1
- pretty-show-1.7
- primitive-0.6.4.0
- profunctors-5.3
- random-1.1
- reflection-2.1.4
- resourcet-1.2.1
- semigroupoids-5.3.1
- semigroups-0.18.5
- StateVar-1.1.1.0
- syb-0.7
- tagged-0.8.6
- tasty-expected-failure-0.11.1.1
- tasty-hedgehog-0.2.0.0
- tasty-hunit-0.10.0.1
- terminal-size-0.3.2.1
- th-abstraction-0.2.8.0
- th-lift-0.7.10
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- unbounded-delays-0.1.1.0
- unique-0
- unliftio-core-0.1.1.0
- unordered-containers-0.2.9.0
- vector-0.12.0.1
- void-0.7.2
- wcwidth-0.0.2
- wl-pprint-annotated-0.1.0.0

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra global and per-package GHC options
# ghc-options: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

